name: ci
on:
  - pull_request
  - push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6.0.2
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
